version: '3.7'
services:
  btc-bitcoin-core:
    image: kylemanna/bitcoind
    restart: always
    ports:
      - "8332:8332"
      - "18332:18332"
    volumes:
      - "$PWD/example/.bitcoin:/bitcoin/.bitcoin"
    command: bitcoind
  eth-geth:
    image: ethereum/client-go
    restart: always
    ports:
      - "8545:8545"
    volumes:
      - "$PWD/example/.ethereum:/root/.ethereum"
    command: --rinkeby --rpc --rpcapi "personal" --rpcaddr 0.0.0.0
