dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
script:
  - pipenv install --dev
  - pipenv run pip freeze
  - pytest -vrs
  - pylint --rcfile=pylintrc tests cryptocurrency
