dist: xenial
language: python
python:
- 3.7-dev
- '3.8'
- 3.8-dev
install:
- pip install -e .[dev]
script:
- pylint tests django_obm -d C
- pytest -vrs
deploy:
  provider: pypi
  skip_existing: true
  user: "__token__"
  password:
    secure: C3QEpT/hX9cZ/wP1CdmzfU1PNqHCzItV/MYA/k+mhHdl9wF+p8N8cXa6Qjyk8E/udkJ9D07xXxWgONy0Wk0XAC6++tGDIG/erVrVCbQ+hMQFnjWNKo+2nklLcBObbGddugnx04GRo4oiZbUAJTunD+fZjSzCLSAd1wPFX7akwbjhRpSH3j0/150ZdphZnpZslZFIls+9YCSDYHVvbpsP91KBPWrPxhG55Ff3x7re8/osQWpPhlBqhDUeuwRYKux+0cPXh787TL4a/rXZ+2YzE6E+ue5BVOXHsQX411eV2aj8E96RY7XrPdeYYjMK9AYzwE5FLo6nM3dD3NYiEmgs72npM1NZlT2xxiDzdG1Qj3FcGpElLryecEzVYbOLUnkDbbLpNRCQPHPxW2/guRxjp/ntnmoRuWCu855GmYNcimdfcT6IlghmxqVmjs2745+Z0vjp4yWrYshGZ2rkCNFXCT09dWhsp3uXXTNvKM1ozNm8QjppyRz+gSKDADarS+JfknOXiCqiGddvzyci1jGE9UBhLZSB3LTPSKB5qA2X3vNhVuNnWgL4npwtC8uZ46z+7b4beh8oi6bBdIcZ10N+GBSIp7arMCQNVEB1hx17dw6T1C5AauIm4Pzn0G2CLt1VuXK8L5jBlqX+4tlFkptrNk5fdFVbW3J/bskXJhp7VRI=
  on:
    branch: master
