dist: xenial
language: python
python:
- '3.8'
- 3.8-dev
install:
- pip install -e .[dev]
script:
- pylint tests django_obm -d C
- pytest -vrs
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: G8Wz95rRQezYThymxqUgsJgdQ43NkoR5rQARQMUAFv8uoqP1Zh/+OdOzImKXEhM6TsyvOroUrkLs0NS9ADKyZs0eFUFN3XnU/i8LmAKm6AXts4BHyQkwpiC1sVeqdbtM5heuDAANQYmnN+1Koms8xw7uFqSRWZw2+oTFr8/5tccgD189Nz39BzNb19CFfHKkJrEHgipZRXpRvb0eSldmjyu1NuGEbBZTnrl/mGHle1y/vYUHo/ADIs6j8qcb9Ly6YgFIbcFlWxffKUZpPwhimvM5crunWpYKA3YYZlFQBTb/Q4WbT55/YNhm0XSfuK6wc4MNyDojTSYGv9LH5iwVAD6tARC1G+SYr20x+16cQHtmMBDuvBmvjbTbQVlMyXD0Czx0vs6g19HSfLuVL/wO5jqjd5Tv1hKKy27jgJXxtSOMrqD2pE4GTKv/zZNOAnsRMQnWzwxupJ786/MyoQjq35jEbSTANigjSApK+7O4YabuQuL7XwDWgncenstH+/Qjtc5V37dLPGEpwFrondbJmbr+1V2tyoyutK75q2LkOTtWEVsn0aXcr5F6OhWSRbUOe/wtk7zU+zY6TTchZQ9kXVDkmU8aYYZj5F5PCv+5zU4t1O2rIsableYwipH4Z4Vo/3svzQA6XYE5vFdUHATLvKlmc8e7fuVVx+IA7nQIlhI=
  on:
    branch: master
