dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
install:
  - pipenv install --dev --deploy
script:
  - python --version
  - pipenv run testing
  - pipenv run linting
