dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
install:
  - pipenv sync --dev
script:
  - python --version
  - pytest -vrs
  - pylint --rcfile=pylintrc tests cryptocurrency
